const papers = [
 {id:'attention',title:'Attention Is All You Need',year:'2017',authors:'Vaswani et al.',url:'https://arxiv.org/abs/1706.03762',place:'The little library',x:22,y:40,w:15,h:26,clue:'A very small library. A very large attention span.',note:'You found a book that pays attention to all the other books.',summary:'The paper that introduced the Transformer: a sequence-modeling architecture built around attention, without recurrent or convolutional layers. A foundational idea behind modern language models.'},
 {id:'fewshot',title:'Language Models are Few-Shot Learners',year:'2020',authors:'Brown et al.',url:'https://arxiv.org/abs/2005.14165',place:'The compute greenhouse',x:73,y:37,w:14,h:25,clue:'Something is scaling in the greenhouse. It might be the electricity bill.',note:'The plants asked for sunlight. Someone ordered more GPUs.',summary:'The GPT-3 paper explored how scaling language models could enable new tasks through examples in the prompt, without updating the model’s weights for each task.'},
 {id:'feedback',title:'Training language models to follow instructions with human feedback',year:'2022',authors:'Ouyang et al.',url:'https://arxiv.org/abs/2203.02155',place:'The reflection pond',x:70.4,y:61.5,w:7,h:10,clue:'The pond has some feedback. Try listening to the duck.',note:'One quack for helpful. Two quacks for please bring bread.',summary:'An investigation of instruction-following through supervised fine-tuning and reinforcement learning from human feedback. Human preferences help shape which responses the model learns to produce.'},
 {id:'dpo',title:'Direct Preference Optimization',year:'2023',authors:'Rafailov et al.',url:'https://arxiv.org/abs/2305.18290',place:'The suspicious haystack',x:43,y:44,w:10,h:17,clue:'Somewhere in the hay, there is a more direct approach.',note:'A needle in a haystack. The needle preferred being found.',summary:'Your Language Model is Secretly a Reward Model. This paper develops a way to learn from preference data with a direct classification objective, simplifying the usual reward-model-and-RL pipeline.'},
 {id:'constitution',title:'Constitutional AI: Harmlessness from AI Feedback',year:'2022',authors:'Bai et al.',url:'https://arxiv.org/abs/2212.08073',place:'The abandoned field book',x:49,y:59,w:5,h:9,clue:'Someone left the garden rules open beside the path.',note:'Rule one: be kind. Rule two: do not optimize away the picnic.',summary:'A method for training assistants using a set of written principles, model self-critique, and AI feedback. It explores reducing dependence on human labels for identifying harmful outputs.'},
 {id:'maml',title:'Model-Agnostic Meta-Learning',year:'2017',authors:'Finn, Abbeel & Levine',url:'https://arxiv.org/abs/1703.03400',place:'The very slow race',x:39,y:74,w:10,h:10,clue:'The racers are learning how to learn. This may take a minute.',note:'The snail learned to learn faster. It is still a snail.',summary:'For Fast Adaptation of Deep Networks. MAML trains model parameters so a small number of gradient updates can adapt them to a new task. A classic approach to learning how to learn.'}
];
const $ = s => document.querySelector(s); let found = new Set();
try { const saved=JSON.parse(localStorage.getItem('almost-papers')||'[]');if(Array.isArray(saved)) found=new Set(saved.filter(id=>papers.some(p=>p.id===id))); } catch {}
const dialog=$('#dialog'); let toastTimer;let hintIndex=0;let lastFocus;
function open(content){lastFocus=document.activeElement;$('#dialog-content').innerHTML=content;if(!dialog.open)dialog.showModal();$('#close').focus();}
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),4800);}
function update(){ $('#count').textContent=`${found.size} / ${papers.length}`;papers.forEach(p=>{const b=$(`[data-paper="${p.id}"]`);b.setAttribute('aria-label',`Move ${p.place} to look for a book`);}); }
function discover(p){const isNew=!found.has(p.id);found.add(p.id);try{localStorage.setItem('almost-papers',JSON.stringify([...found]));}catch{}update();open(`<div class="eyebrow">${isNew?'A SMALL DISCOVERY':'FROM YOUR FIELD NOTES'} · ${p.year}</div><h2 id="dialog-title">${p.title}</h2><div class="paper-meta">${p.authors} / ${p.year}</div><p>${p.summary}</p><p class="discovery">${p.note}</p><a class="paper-link" href="${p.url}" target="_blank" rel="noopener noreferrer">Read the original paper ↗</a><p style="font-size:11px">${found.size===6?'All six found. A remarkably productive day of wandering.':`${found.size} of 6 papers tucked into your field notes.`}</p>`);}
const moved = new Set();
const offsets = {attention:[-55,-55],fewshot:[70,-65],feedback:[60,-15],dpo:[65,-20],constitution:[-60,-20],maml:[85,0]};
const colors = ['#a6634a','#697f75','#9b844e','#557d8c','#9b725f','#788653'];
function reveal(p){
 if(moved.has(p.id))return;moved.add(p.id);const [x,y]=offsets[p.id];
 $(`#cover-${p.id}`).classList.remove('dragging');$(`#cover-${p.id}`).style.translate=`${x}px ${y}px`;
 const target=$(`[data-paper="${p.id}"]`);target.classList.add('revealed');target.tabIndex=-1;
 const book=$(`[data-book="${p.id}"]`);book.classList.add('visible');book.tabIndex=0;
 const isNew=!found.has(p.id);found.add(p.id);try{localStorage.setItem('almost-papers',JSON.stringify([...found]));}catch{}update();
 toast(found.size===6?'All six found! The snails are considering you for tenure.':`${isNew?'A book!':'There it is again!'} Click it to read the paper. (${found.size}/6 found)`);
}
papers.forEach((p,i)=>{
 const book=document.createElement('a');book.className='hidden-book';book.dataset.book=p.id;book.href=p.url;book.target='_blank';book.rel='noopener noreferrer';book.tabIndex=-1;book.setAttribute('aria-label',`Read ${p.title} (opens in a new tab)`);book.style.cssText=`left:${p.x}%;top:${p.y}%;--book-color:${colors[i]}`;book.innerHTML='<span class="book-cover" aria-hidden="true">'+['a','✳','≈','↗','§','∞'][i]+'</span>';$('#books').append(book);
 const b=document.createElement('button');b.className='hotspot';b.dataset.paper=p.id;b.dataset.label='Drag or tap to investigate';b.style.cssText=`left:${p.x}%;top:${p.y}%;width:${p.w}%;height:${p.h}%`;$('#hotspots').append(b);
 let start=null;
 b.addEventListener('pointerdown',e=>{start={x:e.clientX,y:e.clientY};b.setPointerCapture(e.pointerId);});
 b.addEventListener('pointermove',e=>{if(!start)return;const dx=e.clientX-start.x,dy=e.clientY-start.y;if(Math.hypot(dx,dy)>5){const ratio=1200/$('#scene').getBoundingClientRect().width;const cover=$(`#cover-${p.id}`);cover.classList.add('dragging');cover.style.translate=`${dx*ratio}px ${dy*ratio}px`;}});
 b.addEventListener('pointerup',()=>{if(start){start=null;reveal(p);}});
 b.addEventListener('pointercancel',()=>{start=null;$(`#cover-${p.id}`).classList.remove('dragging');$(`#cover-${p.id}`).style.translate='0px 0px';});
 b.addEventListener('click',()=>reveal(p));
});update();
const reset=document.createElement('button');reset.className='reset-garden';reset.textContent='Hide the books again ↻';reset.onclick=()=>{moved.clear();papers.forEach(p=>{$(`#cover-${p.id}`).style.translate='0px 0px';const b=$(`[data-paper="${p.id}"]`);b.classList.remove('revealed','hinted');b.tabIndex=0;const book=$(`[data-book="${p.id}"]`);book.classList.remove('visible');book.tabIndex=-1;});toast('Everything is back in its unlikely place. Your field notes are safe.');};$('.garden-tools').append(reset);
$('#close').onclick=()=>dialog.close();dialog.addEventListener('close',()=>lastFocus?.focus());dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();}});
$('#notebook').onclick=()=>{open(`<div class="eyebrow">COLLECTED WHILE WANDERING · ${found.size} / 6</div><h2 id="dialog-title">Your field notes.</h2><p>${found.size?'A few ideas worth taking home.':'An empty notebook is a lovely place to start. Drag or tap the objects in the garden to uncover your first book.'}</p><ul class="entries">${papers.map(p=>found.has(p.id)?`<li><small>${p.year} · ${p.place}</small><button data-entry="${p.id}">${p.title} ↗</button></li>`:`<li class="locked">Undiscovered / ${p.place}</li>`).join('')}</ul><p style="font-size:11px">Saved in this browser, when local storage is available. No account, no tracking.</p>`);document.querySelectorAll('[data-entry]').forEach(b=>b.onclick=()=>discover(papers.find(p=>p.id===b.dataset.entry)));};
$('#about').onclick=()=>open(`<div class="eyebrow">WELCOME TO ALMOST</div><h2 id="dialog-title">Big questions.<br>Small ambitions.</h2><p>Everyone is racing toward superintelligence. We thought there should be somewhere to sit down along the way.</p><p>This is the Institute of Almost Superintelligence: an imaginary research garden, populated by very real papers and slightly underqualified snails.</p><p>Drag or tap objects to move them aside. Six tiny books hide underneath. Click an uncovered book to open its original paper in a new tab. Each discovery also gets a page in your field notes. There is no time limit. There is, in fact, very little urgency.</p><p class="discovery">An independent art project. Not affiliated with Sam Altman, OpenAI, or any AI laboratory. The snails speak for themselves.</p>`);
$('#colophon').onclick=()=>open(`<div class="eyebrow">A NOTE FROM THE GARDENER</div><h2 id="dialog-title">A softer corner<br>of the internet.</h2><p>Original illustrations, a few quiet interactions, and a fondness for big ideas in small places.</p><p>Inspired by the gentle, playful worlds of <a href="https://www.baothiento.com/" target="_blank" rel="noopener noreferrer">Bao To</a>. Built as an independent internet daydream at altman.si.</p><p>Paper titles and links lead to the authors’ original work. This garden is a tiny curated reading trail, not a ranking of progress toward superintelligence.</p><p><a href="https://github.com/boovines/altman-si" target="_blank" rel="noopener noreferrer">Visit the source code ↗</a></p>`);
$('#hint').onclick=()=>{const remaining=papers.filter(p=>!moved.has(p.id));if(!remaining.length){toast('You found them all. The garden is still yours to enjoy.');return;}const p=remaining[hintIndex++%remaining.length];document.querySelectorAll('.hinted').forEach(b=>b.classList.remove('hinted'));$(`[data-paper="${p.id}"]`).classList.add('hinted');toast(p.clue);};
let paused=matchMedia('(prefers-reduced-motion: reduce)').matches;function motion(){document.body.classList.toggle('paused',paused);$('#motion').setAttribute('aria-pressed',String(paused));$('#motion').innerHTML=paused?'Let the breeze in <span>▷</span>':'Pause the breeze <span>Ⅱ</span>';}motion();$('#motion').onclick=()=>{paused=!paused;motion();};
const bulletins=['The snails have requested more compute.','The library is open. The future is not peer-reviewed.','A breakthrough is expected shortly. Please have some tea.','The duck has declined to comment on scaling laws.','The finish line has been moved. Again.','The greenhouse is experiencing emergent tomatoes.'];let bulletin=0;$('#next-status').onclick=()=>$('#status').textContent=bulletins[++bulletin%bulletins.length];
// Deterministic planting: the same small garden on every visit.
let seed=42;const random=()=>{seed=(seed*16807)%2147483647;return(seed-1)/2147483646;};let planting='';for(let i=0;i<100;i++){let x=130+random()*920,y=210+random()*300;if(((x-600)/500)**2+((y-345)/220)**2>1)continue;planting+=`<path d="M${x} ${y}l-2-6m2 6l4-8" stroke="#8f9f72" opacity=".45" stroke-width="1"/>`;if(i%4===0)planting+=`<use href="#flower" transform="translate(${x} ${y}) scale(${.6+random()*.5})"/>`;}[[172,304,.85],[370,236,.65],[962,311,.8],[780,226,.48],[997,399,.57],[199,431,.45]].forEach(([x,y,s])=>planting+=`<use href="#tree" transform="translate(${x} ${y}) scale(${s})"/>`);$('#vegetation').innerHTML=planting;
